<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>TestRunner.NUnitTestRunnerProxy.Server</AssemblyName>
    <RootNamespace>TestRunner.NUnitTestRunnerProxy.Server</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TestRunner.NUnitTestRunnerProxy\TestRunner.NUnitTestRunnerProxy.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="TestRunner.NUnitTestRunnerProxy.X.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="CopyExchangeFiles" AfterTargets="Build">
    <PropertyGroup>
      <DestinationDir>$(ExchangeDir)TestRunner.NUnitTestRunnerProxy.X\</DestinationDir>
    </PropertyGroup>
    <ItemGroup>
      <OutFile Include="$(TargetDir)\**\*" />
    </ItemGroup>
    <RemoveDir Directories="$(DestinationDir)" />
    <Copy SourceFiles="@(OutFile)" DestinationFiles="$(DestinationDir)%(OutFile.RecursiveDir)%(OutFile.Filename)%(OutFile.Extension)" />
  </Target>
</Project>
