<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<!-- StyleCop configuration -->
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)\StyleCop.json" />
	</ItemGroup>
	
	<Target Name="IncludeNUnitTestRunnerProxyDirOutput" Condition="$(IncludeNUnitTestRunnerProxyDirOutput) == 'true'" BeforeTargets="AssignTargetPaths">
		<ItemGroup>
			<_NUnitTestRunnerProxyFile Include="$(NUnitTestRunnerProxyDir)**\*" />
			<Content Include="@(_NUnitTestRunnerProxyFile)" Link="%(_NUnitTestRunnerProxyFile.RecursiveDir)%(_NUnitTestRunnerProxyFile.Filename)%(_NUnitTestRunnerProxyFile.Extension)" CopyToOutputDirectory="Always" />
		</ItemGroup>
	</Target>
</Project>