<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AssemblyName>TestRunner.App</AssemblyName>
		<RootNamespace>TestRunner.App</RootNamespace>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Freemanke.Xmlrpc" Version="1.0.1" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.69" />
		<PackageReference Include="InputSimulatorPlus.NetStandard" Version="1.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
		<PackageReference Include="NUnit" Version="4.1.0" />
		<PackageReference Include="NUnit.Engine" Version="3.18.3" />
		<PackageReference Include="Spectre.Console" Version="0.49.2-preview.0.44" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DevKit\DevKit\DevKit.csproj" />
		<ProjectReference Include="..\TestRunner.Common\TestRunner.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="TestLinkApi\TODO = REFACOR" />
		<None Include="TestLinkApi\TODO = REFACOR" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	
	<!-- COM -->
	<ItemGroup>
		<Content Include="TestRunner.App.manifest">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		
		<!-- Include COM server output from "echange" dir -->
		<Content Include="$(ExchangeDir)**\*" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<!-- Flatten essential reg-free COM files to the app output root -->
	<Target Name="CopyRegFreeComToOutput" AfterTargets="Build">
		<ItemGroup>
			<_ComFilesToRoot Include="$(ExchangeDir)TestRunner.NUnitTestRunnerProxy.X\TestRunner.NUnitTestRunnerProxy.X.manifest" />
			<_ComFilesToRoot Include="$(ExchangeDir)TestRunner.NUnitTestRunnerProxy.X\TestRunner.NUnitTestRunnerProxy.Server.exe" />
		</ItemGroup>
		<Copy SourceFiles="@(_ComFilesToRoot)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
	</Target>
</Project>
