//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRunner.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestRunner.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IDE install folder path.
        /// </summary>
        public static string EnterIdeInstallFolderPath_ChoiceText {
            get {
                return ResourceManager.GetString("EnterIdeInstallFolderPath_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE install folder path.
        /// </summary>
        public static string IdeInstallFolderPath_ChoiceText {
            get {
                return ResourceManager.GetString("IdeInstallFolderPath_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE version.
        /// </summary>
        public static string IdeVersion_ChoiceText {
            get {
                return ResourceManager.GetString("IdeVersion_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up and down to reveal more choices.
        /// </summary>
        public static string MoveUpAndDownToReveal_HelpText {
            get {
                return ResourceManager.GetString("MoveUpAndDownToReveal_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No runtimes found under IDE install folder.
        /// </summary>
        public static string NoRuntimesFoundUnderIdeInstallFolder_Message {
            get {
                return ResourceManager.GetString("NoRuntimesFoundUnderIdeInstallFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty or does not exist.
        /// </summary>
        public static string PathCanNotBeEmpty_ErrorMessage {
            get {
                return ResourceManager.GetString("PathCanNotBeEmpty_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path doesn&apos;t exist.
        /// </summary>
        public static string PathDoesNotExist_ErrorMessage {
            get {
                return ResourceManager.GetString("PathDoesNotExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue ....
        /// </summary>
        public static string PressAnyKeyToContinue_Message {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test.
        /// </summary>
        public static string RunTest_ChoiceText {
            get {
                return ResourceManager.GetString("RunTest_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version.
        /// </summary>
        public static string RuntimeVersion_ChoiceText {
            get {
                return ResourceManager.GetString("RuntimeVersion_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select test cases.
        /// </summary>
        public static string SelectTestCases_ChoiceText {
            get {
                return ResourceManager.GetString("SelectTestCases_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select test suites.
        /// </summary>
        public static string SelectTestSuites_ChoiceText {
            get {
                return ResourceManager.GetString("SelectTestSuites_ChoiceText", resourceCulture);
            }
        }
    }
}
